image: 
  - Visual Studio 2015

init:
  - date /T & time /T
  - git config --global core.autocrlf input
  - cmake --version
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      else
      {
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.substring(0,7))"
      }

clone_folder: c:\projects\cpp-benchmarks

branches:
  only:
  - master

clone_depth: 5

version: '{build}'

platform:
  - x86
  - x64

configuration:
  - Release

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  BOOST_ROOT: C:/Libraries/boost_1_59_0
  matrix:
    - generator: "Visual Studio 14"    

matrix:
  exclude: 
    - image: Visual Studio 2015
      generator: "Visual Studio 15"
  fast_finish: false

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - dir
  - cd.. 
  - mkdir build
  - cd build
  - >
    cmake %APPVEYOR_BUILD_FOLDER%
    -G "%generator%" 
  - cmake --build . --target ALL_BUILD --config %configuration% -- /nologo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

